### ISSUE TITLE
duplicate module on another page 

### ISSUE THREAD

**Issue by chassain** [eouia/MMM-Widget#3]
Hello,

i would like to duplicate your module in an another page with mmm-pages. normally i duplicate folder and rename MMM-Widget2, change mmm.widget2.js and rename the register..but no way here..i don't understand..
I need to have a widget on page 1 and other widget on page 2.

Thanks for help.

**Comment by chassain** [comment]
or maybe are you a evolution to slide differents html in the same module...

**Comment by eouia** [comment]
Hmmm. at this moment, MMM-Widget is hard to be duplicated. Maybe I can write a new module like `MMM-WidgetLite` something for easy duplication. but I cannot guarantee it could be soon or not.

**Comment by chassain** [comment]
It will be great...Have a good day ! thanks from France

**Comment by eouia** [comment]
Try to this;
https://github.com/eouia/MMM-Widget2

**Comment by chassain** [comment]
Perfect..it works...thanks a lot..
